name: Group PRs by Dependencies

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]

jobs:
  group_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get PR labels
        id: pr_labels
        uses: actions/github-script@v4
        with:
          script: |
            const { data: labels } = await github.pulls.listLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            const labelNames = labels.map((label) => label.name);
            console.log(labelNames.join(','));
          outputs:
            labels: ${{ steps.pr_labels.outputs.result }}

      - name: Get version bump
        id: version_bump
        run: echo "::set-output name=bump::$(git diff --name-only HEAD^ HEAD | grep 'package.json' | xargs cat | jq '.version' | awk -F '"' '{print $2}' | awk -F '.' '{print $NF}')"

      - name: Create PR
        if: contains(steps.pr_labels.outputs.labels, 'dependencies')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          case "${{ steps.version_bump.outputs.bump }}" in
            patch)
              echo "This is a patch update"
              # Add your code to handle patch update here
              ;;
            minor)
              echo "This is a minor update"
              # Add your code to handle minor update here
              ;;
            major)
              echo "This is a major update"
              # Add your code to handle major update here
              ;;
            *)
              echo "Invalid version bump"
              exit 1
              ;;
          esac
          git config user.email "dependabot@github.com"
          git config user.name "Dependabot"
          git checkout -b dependabot/bump-dependencies
          git add package.json
          git commit -m "Bump dependencies"
          git push -u origin dependabot/bump-dependencies